### ISSUE TITLE
finding client_id/client_secret no longer needed?

### ISSUE THREAD

**Issue by ahmetb** [rccoleman/lmdirect#34]
Readme says:

> Find the client_id and client_secret for your machine by following [these instructions](https://github.com/rccoleman/lmdirect/blob/master/Credentials.md).

but as you found out in your  https://github.com/rccoleman/lamarzocco repo , the client_id/client_secret is the same for everyone using the iOS app (edit: it seems you tested this on Android –but it seems like it's the same for iOS based on my mitmdump). I assume these instructions are redundant?

**Comment by rccoleman** [comment]
They're not redundant or unnecessary, as they're the real way to find the `client_id` and `client_secret`, but the ones that I found and added to the docs work for now and maybe forever.

**Comment by ahmetb** [comment]
Ack, thanks.
I also noticed that there don't seem to be instructions around finding out the IP address/port of the machine to construct `config.json` in the README.

**Comment by rccoleman** [comment]
Yeah, that's something that you'll need to figure out if you're using the library directly.  The Home Assistant integration, which I built this for, uses zeroconf to find your machine and doesn't need the user to know the IP address or port.
