### ISSUE TITLE
Callback when extraction is started/ stopped

### ISSUE THREAD

**Issue by ilpantera** [rccoleman/lmdirect#36]
Hi,

> Users can register for a callback when new data is received.

Is it possible to receive a callback when the extraction is started/ stopped?

**Comment by rccoleman** [comment]
That would require keeping the connection to the machine open continuously, which I currently do not.  I prefer to open the connection when I need to poll or send another command, wait for a response, and then close it to allow users to use the official app in conjunction with this library if they wish.  Keeping the connection open all the time would preclude that.

The machine does stream messages started with "Z" while the pump is engaged and I've decoded them, so it would be possible to add such callbacks if there was also an option to maintain the connection at all times.  Others have requested something similar and I'll consider making the connection mode an option.

**Comment by ilpantera** [comment]
Hi, thanks for the response, For the Linea Micra, this has been implemented here now: https://github.com/zweckj/lmcloud
