### ISSUE TITLE
ModuleNotFoundError: No module named 'authlib'

### ISSUE THREAD

**Issue by bekaxe** [rccoleman/lmdirect#37]
Hi, 

thank you for providing a script for local access! 
- I was able to retrieve client_id and secret and created my config.json file. 
- I copied all files into a local folder, incl. the config.json file. 
- from that folder I am executing python3 test.py

I am now getting the following error when running the test.py script. 

```
Traceback (most recent call last):
  File "/Users/xxx/Downloads/marzocco/test.py", line 1, in <module>
    from lmdirect import LMDirect
  File "/Users/xxx/Downloads/marzocco/lmdirect/__init__.py", line 13, in <module>
    from .connection import Connection
  File "/Users/xxx/Downloads/marzocco/lmdirect/connection.py", line 7, in <module>
    from authlib.integrations.base_client.errors import OAuthError
ModuleNotFoundError: No module named 'authlib'
```

Would be great if you could help me in getting this fixed.

**Comment by rccoleman** [comment]
Looks like you're missing the authlib package :). Did you install the requirements with `pip install -r requirements.txt?`

In any case, this library doesn't work with the latest machine firmware updates, and users were forced to update to maintain access to the mobile app. It most likely won't work for you anymore.

**Comment by bekaxe** [comment]
Thanks, I missed that as I was only following the readme.md. 

Is the lmcloud project also supporting the Linea Mini? It says only Micra...

**Comment by rccoleman** [comment]
Yes, GS/3, Micra, and Mini. The Micra was the first to ship with the new firmware, so that's why it's called out specifically. As of mid-Sept, all machines must be updated to maintain app compatibility.

**Comment by rccoleman** [comment]
I'm archiving this repo as it's not compatible with current firmware on any machine.
